export const OPEN_MODAL="OPEN_MODAL";
export const CLOSE_MODAL="CLOSE_MODAL";
export const CLEAR_CURRENT_USER="CLEAR_CURRENT_USER";
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const UPDATE_USER_INFO="UPDATE_USER_INFO";
