export const SET_PHOTOS="SET_PHOTOS";
export const SET_EVENTSTAB="SET_EVENTSTAB";
export const SET_PROFILE="SET_PROFILE";
export const ALREADY_FOLLOWING="ALREADY_FOLLOWING";
export const ALREADY_UNFOLLOWING="ALREADY_UNFOLLOWING";
export const SET_FOLLOWINGS="SET_FOLLOWINGS";
export const SET_FOLLOWERS="SET_FOLLOWERS";
